on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: ./node_modules/.bin/tsc -p .
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
